# Use postgres/example user/password credentials
version: '3.1'

services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/productionplanning_data_db migrate
    volumes:
      - ./apps/database/flyway.conf:/flyway/conf/flyway.conf
      - ./apps/database/migrations:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $LAPOLLO_DB_PWD
      POSTGRES_USER: $LAPOLLO_DB_USER
      POSTGRES_DB: $LAPOLLO_DB_NAME
    volumes:
      - planner_db_volume:/var/lib/postgresql/data
      - ./apps/database/initialize.sql:/docker-entrypoint-initdb.d/init_postgresql.sql
    ports:
      - 5432:5432
volumes:
  planner_db_volume:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: $LAPOLLO_DB_DIR